### ISSUE TITLE
NixieTap does not boot after flashing firmware 1.1

### ISSUE THREAD

**Issue by jdonny12** [mladendinic/nixietap#8]
Hi Mladen,

I wanted to test the new firmware V1.1, but after flashing it my devices does not boot.

It does not shows the running dot and no WiFi is seen. I can not connect to configure it.

Flashing old firmware V1.0 restores function but has the known issue of date default view.

Thanks.

**Comment by pojzn** [comment]
Hi there,

what you can try is installing Python on your pc (from python.org), and when it's installed open up a terminal. Type "pip install esptool", and when that finishes type "esptool erase_flash". After this, try uploading V1.1.

Hope this helps

**Comment by jdonny12** [comment]
Hi pojzn,

many thanks, that fixed the problem after flashing and the device boots again.

Too bad, the new firmware did not fix the problem of the default date view. I checked the pcb and the wire was already cut on my prebuild device.

**Comment by jdonny12** [comment]
Hmm, back on V1.0. 

After a power loss device did not boot again and a reset did not activate the access point.

**Comment by pojzn** [comment]
I have tried erasing my flash and re-uploading a fresh clone of V1.1 with newly downloaded dependencies, and it seems to work fine, even after rebooting (unplug-plug).
